x-shared-volumes: &shared_volumes
  - ./:/usr/src/app
  - ./data:/usr/src/app/data

services:
  db:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - "5433:5432"


  django:
    build: .
    container_name: django
    env_file:
      - .env
    volumes: *shared_volumes
    ports:
      - "8001:8001"
    depends_on:
      - db

    command: python manage.py runserver 0.0.0.0:8001


  lux_bot:
    build: .
    container_name: lux_bot
    env_file:
      - .env
    volumes: *shared_volumes
    depends_on:
      - db
      - django

    restart: unless-stopped
    command: python manage.py bot


  celery:
    build: .
    container_name: celery
    env_file:
      - .env
    volumes: *shared_volumes
    depends_on:
      - django
      - db
    command: celery -A config worker --loglevel=info


  celery_beat:
    build: .
    container_name: celery_beat
    env_file:
      - .env
    volumes: *shared_volumes
    depends_on:
      - django
      - db
    command: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler


  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"


volumes:
  db: